<?php

declare(strict_types=1);

return [
    'name' => 'int_twilio_sms',
    'display_name' => 'Twilio SMS',
    'version' => '1.0.0',
    'type' => 'integration',
    'provider' => 'Twilio',
    'tool' => 'Programmable Messaging',
    'description' => 'Provides Twilio SMS/MMS transport, status callback support, message lookup, scheduled-message cancellation, and webhook verification to Venny I/O.',
    'purpose' => 'Provide Venny I/O communications workers with a reusable Twilio messaging transport while keeping Twilio credentials, sender selection, Messaging Service routing, SMS/MMS request construction, provider responses, message retrieval, scheduled cancellation, and signed webhook validation isolated from queue and business-domain logic.',
    'tool_url' => 'https://www.twilio.com/docs/messaging',
    'documentation' => [
        'https://www.twilio.com/docs/messaging',
        'https://www.twilio.com/docs/messaging/quickstart',
        'https://www.twilio.com/docs/usage/webhooks/webhooks-security',
        'https://github.com/twilio/twilio-php',
    ],
    'configuration' => [
        [
            'key' => 'v_TWILIO_ACCOUNT_SID',
            'label' => 'Twilio Account SID',
            'required' => true,
            'secret' => false,
            'purpose' => 'Identifies the Twilio account used by Venny I/O.',
            'where_to_obtain' => 'Twilio Console account dashboard.',
            'setup_instructions' => [
                'Sign in to the Twilio Console.',
                'Open the account dashboard or account settings.',
                'Copy the Account SID for the account Venny I/O should use.',
                'Store it as v_TWILIO_ACCOUNT_SID.',
            ],
            'expected_format' => 'AC followed by the Twilio account identifier.',
            'validation_guidance' => 'Must begin with AC.',
            'documentation_url' => 'https://www.twilio.com/docs/usage/requests-to-twilio',
            'notes' => 'Not treated as a secret, but should still be managed as configuration.',
        ],
        [
            'key' => 'v_TWILIO_AUTH_TOKEN',
            'label' => 'Twilio Auth Token',
            'required' => true,
            'secret' => true,
            'purpose' => 'Authenticates Twilio REST API requests and validates Twilio webhook signatures.',
            'where_to_obtain' => 'Twilio Console account credentials.',
            'setup_instructions' => [
                'Open the Twilio Console for the target account.',
                'Locate the account Auth Token.',
                'Reveal/copy the token through the Twilio credential controls.',
                'Store it as v_TWILIO_AUTH_TOKEN.',
                'Do not place it in source control or logs.',
            ],
            'expected_format' => 'Twilio-generated Auth Token.',
            'validation_guidance' => 'Must be present for REST API requests and webhook validation.',
            'documentation_url' => 'https://www.twilio.com/docs/usage/requests-to-twilio',
            'notes' => 'Secret.',
        ],
        [
            'key' => 'v_TWILIO_MESSAGING_SERVICE_SID',
            'label' => 'Twilio Messaging Service SID',
            'required' => false,
            'secret' => false,
            'purpose' => 'Provides the preferred sender abstraction for outbound Venny SMS/MMS.',
            'where_to_obtain' => 'Twilio Console > Messaging > Services.',
            'setup_instructions' => [
                'Open Messaging > Services in the Twilio Console.',
                'Create or select the Messaging Service Venny I/O should use.',
                'Add the appropriate sender resources to the service.',
                'Complete any required sender/campaign configuration for the target countries and use cases.',
                'Copy the Messaging Service SID.',
                'Store it as v_TWILIO_MESSAGING_SERVICE_SID.',
            ],
            'expected_format' => 'MG followed by the Messaging Service identifier.',
            'validation_guidance' => 'Must begin with MG.',
            'documentation_url' => 'https://www.twilio.com/docs/messaging/services',
            'notes' => 'Recommended over coupling Venny to one phone number.',
        ],
        [
            'key' => 'v_TWILIO_FROM_NUMBER',
            'label' => 'Twilio From Number',
            'required' => false,
            'secret' => false,
            'purpose' => 'Provides a fixed Twilio sender when a Messaging Service is not used.',
            'where_to_obtain' => 'Twilio Console > Phone Numbers > Manage > Active numbers.',
            'setup_instructions' => [
                'Acquire or select a Twilio phone number with messaging capability.',
                'Confirm the number is appropriate and registered for the intended messaging use case.',
                'Copy the number in E.164 format.',
                'Store it as v_TWILIO_FROM_NUMBER.',
            ],
            'expected_format' => '+12145551212',
            'validation_guidance' => 'Must be E.164. Either this key or v_TWILIO_MESSAGING_SERVICE_SID must be configured.',
            'documentation_url' => 'https://www.twilio.com/docs/phone-numbers',
            'notes' => 'Fallback sender when no Messaging Service SID is configured.',
        ],
        [
            'key' => 'v_TWILIO_STATUS_CALLBACK_URL',
            'label' => 'Twilio Status Callback URL',
            'required' => false,
            'secret' => false,
            'purpose' => 'Receives asynchronous Twilio message lifecycle callbacks such as sent, delivered, or failed.',
            'where_to_obtain' => 'This is a public HTTPS Venny I/O webhook route created for Twilio message status callbacks.',
            'setup_instructions' => [
                'Create or select the Venny I/O webhook endpoint that will receive Twilio message status callbacks.',
                'Ensure the route is publicly reachable over HTTPS.',
                'Ensure the route validates X-Twilio-Signature using this cartridge before trusting the request.',
                'Store the exact externally visible URL as v_TWILIO_STATUS_CALLBACK_URL.',
            ],
            'expected_format' => 'https://api.example.com/webhooks/twilio/messages/status',
            'validation_guidance' => 'Must be a valid public URL. Signature validation requires the exact URL Twilio calls.',
            'documentation_url' => 'https://www.twilio.com/docs/usage/webhooks/getting-started-twilio-webhooks',
            'notes' => 'Optional but recommended when Venny needs delivery lifecycle updates.',
        ],
    ],
    'capabilities' => [
        'send_sms',
        'send_mms',
        'messaging_service',
        'from_number_fallback',
        'status_callback',
        'retrieve_message',
        'cancel_scheduled_message',
        'webhook_signature_validation',
        'health_check',
    ],
    'dependencies' => [
        'php' => '>=8.1',
        'composer' => ['twilio/sdk' => '^8.0'],
    ],
    'health_check_available' => true,
    'configuration_screen_available' => true,
    'owns_sql' => false,
];
