-- app_venny_commerce schema

CREATE TABLE IF NOT EXISTS transactions (
id UUID DEFAULT gen_random_uuid(),
transaction_id VARCHAR(64) NOT NULL UNIQUE PRIMARY KEY,
transaction_attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
transaction_email TEXT NULL,
transaction_firstname TEXT NULL,
transaction_middlename TEXT NULL,
transaction_lastname TEXT NULL,
transaction_phone TEXT NULL,
transaction_address1 TEXT NULL,
transaction_address2 TEXT NULL,
transaction_city TEXT NULL,
transaction_state VARCHAR(50) NULL,
transaction_zip VARCHAR(20) NULL,
transaction_country VARCHAR(80) NOT NULL DEFAULT 'United States of America',
transaction_currency VARCHAR(10) NOT NULL DEFAULT 'usd',
transaction_subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
transaction_discount NUMERIC(12,2) NOT NULL DEFAULT 0,
transaction_tax NUMERIC(12,2) NOT NULL DEFAULT 0,
transaction_total NUMERIC(12,2) NOT NULL DEFAULT 0,
transaction_attemptcount INT NOT NULL DEFAULT 0,
transaction_stripecustomerid TEXT NULL,
transaction_stripecheckoutsessionid TEXT NULL,
transaction_stripepaymentintentid TEXT NULL,
transaction_stripechargeid TEXT NULL,
transaction_cardbrand VARCHAR(40) NULL,
transaction_cardfunding VARCHAR(40) NULL,
transaction_cardlast4 VARCHAR(4) NULL,
transaction_cardcountry VARCHAR(10) NULL,
transaction_paidat TIMESTAMPTZ NULL,
transaction_failedat TIMESTAMPTZ NULL,
transaction_cancelledat TIMESTAMPTZ NULL,
transaction_refundedat TIMESTAMPTZ NULL,
created_by_user_id VARCHAR(64) NOT NULL DEFAULT 'user_8301',
created_for_app_id VARCHAR(64) NOT NULL DEFAULT 'app_8301',
event_id VARCHAR(64) NOT NULL DEFAULT 'event_8301',
process_id VARCHAR(64) NOT NULL DEFAULT 'process_8301',
access VARCHAR(30) NOT NULL DEFAULT 'private',
status VARCHAR(30) NOT NULL DEFAULT 'active',
active INT NOT NULL DEFAULT 1,
time_started TIMESTAMPTZ NOT NULL DEFAULT NOW(),
time_updated TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS orders (
id UUID DEFAULT gen_random_uuid(),
order_id VARCHAR(64) NOT NULL UNIQUE PRIMARY KEY,
order_attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
order_customer_id VARCHAR(64) NULL,
order_totalproduct DECIMAL(12,2) NOT NULL,
order_totaltax DECIMAL(12,2) NOT NULL,
order_totalshipping DECIMAL(12,2) NOT NULL,
order_totaltaxshipping DECIMAL(12,2) NOT NULL,
order_totaladjustment DECIMAL(12,2) NULL,
order_description TEXT NULL,
order_currency TEXT NOT NULL,
order_locked BOOLEAN,
order_address TEXT NULL,
created_by_user_id VARCHAR(64) NOT NULL DEFAULT 'user_8301',
created_for_app_id VARCHAR(64) NOT NULL DEFAULT 'app_8301',
event_id VARCHAR(64) NOT NULL DEFAULT 'event_8301',
process_id VARCHAR(64) NOT NULL DEFAULT 'process_8301',
access VARCHAR(30) NOT NULL DEFAULT 'private',
status VARCHAR(30) NOT NULL DEFAULT 'active',
active INT NOT NULL DEFAULT 1,
time_started TIMESTAMPTZ NOT NULL DEFAULT NOW(),
time_updated TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS coupons (
id UUID DEFAULT gen_random_uuid(),
coupon_id VARCHAR(64) NOT NULL UNIQUE PRIMARY KEY,
coupon_attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
coupon_code VARCHAR(30) NOT NULL UNIQUE,
coupon_description TEXT NOT NULL DEFAULT '',
coupon_discounttype VARCHAR(30) NOT NULL,
coupon_percent NUMERIC(5,2) NULL,
coupon_amount NUMERIC(12,2) NULL,
coupon_currency VARCHAR(10) NOT NULL DEFAULT 'usd',
coupon_minimumamount NUMERIC(12,2) NULL,
coupon_maximumamount NUMERIC(12,2) NULL,
coupon_startsat TIMESTAMPTZ NULL,
coupon_expiresat TIMESTAMPTZ NULL,
coupon_maximumredemptions INT NULL,
coupon_redemptions INT NOT NULL DEFAULT 0,
coupon_subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
coupon_discount NUMERIC(12,2) NOT NULL DEFAULT 0,
coupon_tax NUMERIC(12,2) NOT NULL DEFAULT 0,
coupon_total NUMERIC(12,2) NOT NULL DEFAULT 0,
coupon_attemptcount INT NOT NULL DEFAULT 0,
coupon_stripecustomerid TEXT NULL,
coupon_stripecheckoutsessionid TEXT NULL,
coupon_stripepaymentintentid TEXT NULL,
coupon_stripechargeid TEXT NULL,
coupon_cardbrand VARCHAR(40) NULL,
coupon_cardfunding VARCHAR(40) NULL,
coupon_cardlast4 VARCHAR(4) NULL,
coupon_cardcountry VARCHAR(10) NULL,
coupon_paidat TIMESTAMPTZ NULL,
coupon_failedat TIMESTAMPTZ NULL,
coupon_cancelledat TIMESTAMPTZ NULL,
coupon_refundedat TIMESTAMPTZ NULL,
created_by_user_id VARCHAR(64) NOT NULL DEFAULT 'user_8301',
created_for_app_id VARCHAR(64) NOT NULL DEFAULT 'app_8301',
event_id VARCHAR(64) NOT NULL DEFAULT 'event_8301',
process_id VARCHAR(64) NOT NULL DEFAULT 'process_8301',
access VARCHAR(30) NOT NULL DEFAULT 'private',
status VARCHAR(30) NOT NULL DEFAULT 'active',
active INT NOT NULL DEFAULT 1,
time_started TIMESTAMPTZ NOT NULL DEFAULT NOW(),
time_updated TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS customers (
id UUID DEFAULT gen_random_uuid(),
customer_id VARCHAR(64) NOT NULL UNIQUE PRIMARY KEY,
customer_attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
customer_firstname VARCHAR(255) NOT NULL,
customer_middlename VARCHAR(255) NULL,
customer_lastname VARCHAR(255) NOT NULL,
customer_telephone VARCHAR(30) NULL,
customer_initialcontact TIMESTAMP NULL,
customer_email VARCHAR(255) NULL,
created_by_user_id VARCHAR(64) NOT NULL DEFAULT 'user_8301',
created_for_app_id VARCHAR(64) NOT NULL DEFAULT 'app_8301',
event_id VARCHAR(64) NOT NULL DEFAULT 'event_8301',
process_id VARCHAR(64) NOT NULL DEFAULT 'process_8301',
access VARCHAR(30) NOT NULL DEFAULT 'private',
status VARCHAR(30) NOT NULL DEFAULT 'active',
active INT NOT NULL DEFAULT 1,
time_started TIMESTAMPTZ NOT NULL DEFAULT NOW(),
time_updated TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
