<?php

declare(strict_types=1);

return [
    'name' => 'int_sendgrid_email',
    'display_name' => 'SendGrid Email',
    'version' => '1.0.0',
    'type' => 'integration',
    'provider' => 'Twilio SendGrid',
    'tool' => 'Mail Send API',
    'description' => 'Provides transactional email transport through Twilio SendGrid.',
    'purpose' => 'Provide Venny I/O communications workers with a reusable SendGrid email transport while keeping SendGrid authentication, message construction, provider responses, template delivery, attachment handling, and Event Webhook signature verification isolated from message queue and business-domain logic.',
    'tool_url' => 'https://www.twilio.com/docs/sendgrid/api-reference/mail-send/mail-send',
    'documentation' => [
        'https://github.com/sendgrid/sendgrid-php',
        'https://www.twilio.com/docs/sendgrid/api-reference/mail-send/mail-send',
        'https://www.twilio.com/docs/sendgrid/ui/account-and-settings/api-keys',
        'https://www.twilio.com/docs/sendgrid/ui/account-and-settings/how-to-set-up-domain-authentication',
    ],
    'configuration' => [
        [
            'key' => 'v_SENDGRID_API_KEY',
            'label' => 'SendGrid API Key',
            'required' => true,
            'secret' => true,
            'purpose' => 'Authenticates server-side SendGrid Mail Send API requests.',
            'where_to_obtain' => 'Twilio SendGrid Console > Settings > API Keys.',
            'setup_instructions' => [
                'Sign in to the Twilio SendGrid Console.',
                'Open Settings > API Keys.',
                'Create a new API key for Venny I/O.',
                'Grant only the permissions required by the cartridge, normally Mail Send for transactional delivery.',
                'Copy the key when it is created.',
                'Store it in Venny I/O as v_SENDGRID_API_KEY.',
            ],
            'expected_format' => 'SG....',
            'validation_guidance' => 'Must be present and use the SendGrid SG. key prefix.',
            'documentation_url' => 'https://www.twilio.com/docs/sendgrid/ui/account-and-settings/api-keys',
            'notes' => 'Secret. SendGrid only shows the full API key when it is created.',
        ],
        [
            'key' => 'v_SENDGRID_FROM_EMAIL',
            'label' => 'Default From Email',
            'required' => true,
            'secret' => false,
            'purpose' => 'Provides the default sender address for transactional email.',
            'where_to_obtain' => 'Choose an address covered by SendGrid Sender Authentication or a verified single sender.',
            'setup_instructions' => [
                'Configure Sender Authentication in the SendGrid Console.',
                'Prefer Domain Authentication for production sending.',
                'Verify the sending domain or sender according to SendGrid instructions.',
                'Choose the default transactional sender address.',
                'Store that email address as v_SENDGRID_FROM_EMAIL.',
            ],
            'expected_format' => 'notifications@example.com',
            'validation_guidance' => 'Must be a syntactically valid email address and authorized for the SendGrid account.',
            'documentation_url' => 'https://www.twilio.com/docs/sendgrid/ui/account-and-settings/how-to-set-up-domain-authentication',
            'notes' => 'Provider-side sender authentication is required for reliable production delivery.',
        ],
        [
            'key' => 'v_SENDGRID_FROM_NAME',
            'label' => 'Default From Name',
            'required' => false,
            'secret' => false,
            'purpose' => 'Human-readable sender name used when a message does not override the sender.',
            'where_to_obtain' => 'Defined by the Venny application or brand operating the sender identity.',
            'setup_instructions' => [
                'Choose the sender display name recipients should see.',
                'Store it as v_SENDGRID_FROM_NAME.',
            ],
            'expected_format' => 'Venny Notifications',
            'validation_guidance' => 'Plain text display name.',
            'documentation_url' => 'https://www.twilio.com/docs/sendgrid/api-reference/mail-send/mail-send',
            'notes' => null,
        ],
        [
            'key' => 'v_SENDGRID_REPLY_TO_EMAIL',
            'label' => 'Default Reply-To Email',
            'required' => false,
            'secret' => false,
            'purpose' => 'Provides the default destination for recipient replies.',
            'where_to_obtain' => 'Choose a mailbox monitored by the application or business.',
            'setup_instructions' => [
                'Choose the mailbox that should receive replies.',
                'Store the address as v_SENDGRID_REPLY_TO_EMAIL.',
            ],
            'expected_format' => 'support@example.com',
            'validation_guidance' => 'Must be a syntactically valid email address.',
            'documentation_url' => 'https://www.twilio.com/docs/sendgrid/api-reference/mail-send/mail-send',
            'notes' => null,
        ],
        [
            'key' => 'v_SENDGRID_REPLY_TO_NAME',
            'label' => 'Default Reply-To Name',
            'required' => false,
            'secret' => false,
            'purpose' => 'Provides the display name associated with the default reply-to address.',
            'where_to_obtain' => 'Defined by the Venny application or business.',
            'setup_instructions' => [
                'Choose the reply-to display name.',
                'Store it as v_SENDGRID_REPLY_TO_NAME.',
            ],
            'expected_format' => 'Customer Support',
            'validation_guidance' => 'Plain text display name.',
            'documentation_url' => 'https://www.twilio.com/docs/sendgrid/api-reference/mail-send/mail-send',
            'notes' => null,
        ],
        [
            'key' => 'v_SENDGRID_WEBHOOK_PUBLIC_KEY',
            'label' => 'SendGrid Event Webhook Verification Key',
            'required' => false,
            'secret' => false,
            'purpose' => 'Verifies cryptographically signed SendGrid Event Webhook deliveries.',
            'where_to_obtain' => 'SendGrid Event Webhook security configuration.',
            'setup_instructions' => [
                'Configure the SendGrid Event Webhook endpoint that points to the appropriate Venny webhook route.',
                'Enable signed Event Webhook delivery in SendGrid.',
                'Copy the public verification key provided for webhook signature verification.',
                'Store it as v_SENDGRID_WEBHOOK_PUBLIC_KEY.',
            ],
            'expected_format' => 'SendGrid-provided ECDSA public verification key.',
            'validation_guidance' => 'Required only when signed Event Webhook verification is enabled.',
            'documentation_url' => 'https://www.twilio.com/docs/sendgrid/for-developers/tracking-events/getting-started-event-webhook-security-features',
            'notes' => 'This is a verification public key, not the SendGrid API key.',
        ],
    ],
    'capabilities' => [
        'send_email',
        'send_template_email',
        'multiple_recipients',
        'cc_bcc',
        'reply_to',
        'attachments',
        'custom_headers',
        'custom_args',
        'categories',
        'send_at',
        'tracking_settings',
        'event_webhook_verification',
        'health_check',
    ],
    'dependencies' => [
        'php' => '>=8.1',
        'composer' => ['sendgrid/sendgrid' => '^8.1'],
    ],
    'health_check_available' => true,
    'configuration_screen_available' => true,
    'owns_sql' => false,
];
