-- ---------------------------------------------------------
-- app_venny_cms schema
-- Owns CMS content and related CMS assets.
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS assets (
  id UUID DEFAULT gen_random_uuid(),
  asset_id VARCHAR(64) NOT NULL UNIQUE PRIMARY KEY,
  asset_attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
  asset_object_id VARCHAR(64) NULL,
  asset_object_type TEXT NOT NULL,
  asset_originalfilename TEXT NOT NULL,
  asset_displayname TEXT NULL,
  asset_storageprovider VARCHAR(30) NOT NULL DEFAULT 's3',
  asset_bucket TEXT NOT NULL DEFAULT 'io-venny-assets',
  asset_region VARCHAR(50) NOT NULL DEFAULT 'us-east-2',
  asset_appslug TEXT NOT NULL,
  asset_key TEXT NOT NULL,
  asset_etag TEXT NOT NULL,
  asset_checksum_sha265 TEXT NULL,
  asset_mimetype TEXT NOT NULL DEFAULT 'text/html',
  asset_extension VARCHAR(20) NULL,
  asset_size_bytes BIGINT NULL,
  asset_category VARCHAR(50) NOT NULL DEFAULT 'other',
  asset_purpose VARCHAR(100) NULL,
  asset_visibility VARCHAR(30) NOT NULL DEFAULT 'private',
  asset_uploadstatus TEXT NOT NULL DEFAULT 'uploaded',
  asset_processingstatus VARCHAR(30) NULL,
  asset_processingattempts INT NOT NULL DEFAULT 0,
  asset_processingstartedat TIMESTAMPTZ NULL,
  asset_processedat TIMESTAMPTZ NULL,
  asset_processingerror TEXT NULL,
  asset_uploadedat TIMESTAMPTZ NULL,
  asset_archivedat TIMESTAMPTZ NULL,
  asset_deletedat TIMESTAMPTZ NULL,
  created_by_user_id VARCHAR(64) NOT NULL DEFAULT 'user_8301',
  created_for_app_id VARCHAR(64) NOT NULL DEFAULT 'app_8301',
  event_id VARCHAR(64) NOT NULL DEFAULT 'event_8301',
  process_id VARCHAR(64) NOT NULL DEFAULT 'process_8301',
  access VARCHAR(30) NOT NULL DEFAULT 'private',
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  active INT NOT NULL DEFAULT 1,
  time_started TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  time_updated TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS content (
  id UUID DEFAULT gen_random_uuid(),
  content_id VARCHAR(64) NOT NULL UNIQUE PRIMARY KEY,
  content_attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
  content_startdate TIMESTAMPTZ NULL,
  content_enddate TIMESTAMPTZ NULL,
  content_slug TEXT NOT NULL,
  content_title TEXT NOT NULL,
  content_description VARCHAR(280) NULL,
  content_body TEXT NOT NULL,
  content_tags JSONB NULL,
  content_template TEXT NULL,
  content_visible BOOLEAN NOT NULL DEFAULT true,
  created_by_user_id VARCHAR(64) NOT NULL DEFAULT 'user_8301',
  created_for_app_id VARCHAR(64) NOT NULL DEFAULT 'app_8301',
  event_id VARCHAR(64) NOT NULL DEFAULT 'event_8301',
  process_id VARCHAR(64) NOT NULL DEFAULT 'process_8301',
  access VARCHAR(30) NOT NULL DEFAULT 'public',
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  active INT NOT NULL DEFAULT 1,
  time_started TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  time_updated TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
