<?php

declare(strict_types=1);

return [
    'name' => 'int_google_locations',
    'display_name' => 'Google Locations',
    'version' => '1.0.0',
    'type' => 'integration',
    'provider' => 'Google Maps Platform',
    'tool' => 'Geocoding API',
    'description' => 'Provides address geocoding, reverse geocoding, Place ID location resolution, normalized address components, and coordinates to Venny I/O.',
    'purpose' => 'Provide Venny I/O application cartridges with a reusable Google Maps Platform location-normalization adapter while keeping Geocoding API authentication, HTTPS requests, response validation, address-component parsing, coordinates, and provider-specific status handling isolated from application-domain code.',
    'tool_url' => 'https://developers.google.com/maps/documentation/geocoding',
    'documentation' => [
        'https://developers.google.com/maps/documentation/geocoding',
        'https://developers.google.com/maps/documentation/geocoding/requests-geocoding',
        'https://developers.google.com/maps/documentation/geocoding/requests-reverse-geocoding',
        'https://developers.google.com/maps/api-security-best-practices',
    ],
    'configuration' => [
        [
            'key' => 'v_GOOGLE_MAPS_SERVER_KEY',
            'label' => 'Google Maps Server API Key',
            'required' => true,
            'secret' => true,
            'purpose' => 'Authenticates server-side requests from Venny I/O to the Google Maps Platform Geocoding API.',
            'where_to_obtain' => 'Google Cloud Console > Google Maps Platform / APIs & Services > Credentials.',
            'setup_instructions' => [
                'Sign in to Google Cloud Console and create or select the Google Cloud project that will own Venny I/O Maps Platform usage.',
                'Ensure billing is enabled for the project as required by Google Maps Platform.',
                'Open APIs & Services > Library and enable the Geocoding API.',
                'Open APIs & Services > Credentials and create an API key dedicated to Venny server-side geocoding.',
                'Restrict the key to the Geocoding API.',
                'Apply an appropriate server-side application restriction, such as permitted server IP addresses, when the deployment architecture supports stable egress IP restrictions.',
                'Do not reuse a browser/mobile Maps key for this server-side cartridge.',
                'Store the resulting key in Venny I/O as v_GOOGLE_MAPS_SERVER_KEY.',
            ],
            'expected_format' => 'AIza...',
            'validation_guidance' => 'Must be present, restricted to the intended Google Maps Platform API, and usable from the Venny server environment.',
            'documentation_url' => 'https://developers.google.com/maps/documentation/geocoding/get-api-key',
            'notes' => 'Secret server-side credential. Google recommends separate keys per application and appropriate API/application restrictions.',
        ],
        [
            'key' => 'v_GOOGLE_GEOCODING_LANGUAGE',
            'label' => 'Default Geocoding Language',
            'required' => false,
            'secret' => false,
            'purpose' => 'Provides the default language preference for Geocoding API results when a request does not override it.',
            'where_to_obtain' => 'Choose the language appropriate to the Venny application and audience.',
            'setup_instructions' => [
                'Choose the default language code for geocoding responses.',
                'Store the language code as v_GOOGLE_GEOCODING_LANGUAGE.',
                'Leave unset when Google should determine the response language from the request/provider defaults.',
            ],
            'expected_format' => 'en',
            'validation_guidance' => 'Use a supported language code format.',
            'documentation_url' => 'https://developers.google.com/maps/faq#languagesupport',
            'notes' => 'Optional request preference.',
        ],
        [
            'key' => 'v_GOOGLE_GEOCODING_REGION',
            'label' => 'Default Geocoding Region Bias',
            'required' => false,
            'secret' => false,
            'purpose' => 'Biases forward-geocoding results toward a configured region.',
            'where_to_obtain' => 'Choose the two-character region appropriate to the application deployment or target market.',
            'setup_instructions' => [
                'Choose the default region bias if the Venny application primarily geocodes addresses in one region.',
                'Store the two-character region value as v_GOOGLE_GEOCODING_REGION.',
                'Leave unset when no default regional bias is appropriate.',
            ],
            'expected_format' => 'us',
            'validation_guidance' => 'Must be a two-character region code. Region bias does not guarantee results are limited to that region.',
            'documentation_url' => 'https://developers.google.com/maps/documentation/geocoding/requests-geocoding#RegionCodes',
            'notes' => 'Optional. This is a bias, not a hard geographic restriction.',
        ],
    ],
    'capabilities' => [
        'geocode_address',
        'reverse_geocode',
        'geocode_place_id',
        'normalize_address',
        'get_coordinates',
        'configuration_validation',
        'health_check',
    ],
    'dependencies' => [
        'php' => '>=8.1',
        'extensions' => ['curl', 'json'],
    ],
    'health_check_available' => true,
    'configuration_screen_available' => true,
    'owns_sql' => false,
];
