<?php

declare(strict_types=1);

return [
    'name' => 'int_google_places',
    'display_name' => 'Google Places',
    'version' => '1.0.0',
    'type' => 'integration',
    'provider' => 'Google Maps Platform',
    'tool' => 'Places API (New)',
    'description' => 'Provides Google place discovery, autocomplete, details, text/nearby search, photo URI resolution, and session-token handling to Venny I/O.',
    'purpose' => 'Provide Venny I/O application cartridges with a reusable Google Places API (New) adapter while keeping API authentication, Places endpoints, field-mask requirements, billing-sensitive response selection, Autocomplete session-token mechanics, provider errors, and common place normalization isolated from application-domain logic.',
    'tool_url' => 'https://developers.google.com/maps/documentation/places/web-service/op-overview',
    'documentation' => [
        'https://developers.google.com/maps/documentation/places/web-service/op-overview',
        'https://developers.google.com/maps/documentation/places/web-service/place-autocomplete',
        'https://developers.google.com/maps/documentation/places/web-service/place-details',
        'https://developers.google.com/maps/documentation/places/web-service/text-search',
        'https://developers.google.com/maps/documentation/places/web-service/nearby-search',
        'https://developers.google.com/maps/documentation/places/web-service/place-photos',
        'https://developers.google.com/maps/documentation/places/web-service/choose-fields',
        'https://developers.google.com/maps/api-security-best-practices',
    ],
    'configuration' => [
        [
            'key' => 'v_GOOGLE_MAPS_SERVER_KEY',
            'label' => 'Google Maps Server API Key',
            'required' => true,
            'secret' => true,
            'purpose' => 'Authenticates Venny server-side requests to Places API (New).',
            'where_to_obtain' => 'Google Cloud Console > APIs & Services > Credentials.',
            'setup_instructions' => [
                'Sign in to Google Cloud Console and create or select the Google Cloud project that should own Venny I/O Places usage.',
                'Ensure billing is enabled for that project as required by Google Maps Platform.',
                'Open APIs & Services > Library and enable Places API (New).',
                'Open APIs & Services > Credentials and create an API key dedicated to server-side Venny Places requests.',
                'Restrict the key to Places API (New).',
                'Apply an appropriate server-side application restriction, such as server IP restrictions, when the Venny hosting architecture supports stable egress IPs.',
                'Do not reuse a browser/mobile Maps key for this server-side cartridge.',
                'Store the resulting key as v_GOOGLE_MAPS_SERVER_KEY.',
            ],
            'expected_format' => 'AIza...',
            'validation_guidance' => 'Must be present and authorized for Places API (New).',
            'documentation_url' => 'https://developers.google.com/maps/documentation/places/web-service/get-api-key',
            'notes' => 'Secret server-side credential. Google recommends API and application restrictions.',
        ],
        [
            'key' => 'v_GOOGLE_PLACES_LANGUAGE',
            'label' => 'Default Places Language',
            'required' => false,
            'secret' => false,
            'purpose' => 'Provides the default response language for supported Places API requests.',
            'where_to_obtain' => 'Choose the language appropriate to the consuming Venny application.',
            'setup_instructions' => [
                'Choose the default Places response language for the application.',
                'Store the supported language code as v_GOOGLE_PLACES_LANGUAGE.',
                'Leave unset when request-specific or provider-default language behavior is preferred.',
            ],
            'expected_format' => 'en',
            'validation_guidance' => 'Use a supported Google Maps Platform language code.',
            'documentation_url' => 'https://developers.google.com/maps/faq#languagesupport',
            'notes' => 'Optional.',
        ],
        [
            'key' => 'v_GOOGLE_PLACES_REGION_CODE',
            'label' => 'Default Places Region Code',
            'required' => false,
            'secret' => false,
            'purpose' => 'Supplies a default two-character region code where Places API supports regional result formatting or behavior.',
            'where_to_obtain' => 'Choose the region appropriate to the Venny application or market.',
            'setup_instructions' => [
                'Choose the default two-character region code.',
                'Store it as v_GOOGLE_PLACES_REGION_CODE.',
                'Leave unset when no application-wide region default is appropriate.',
            ],
            'expected_format' => 'US',
            'validation_guidance' => 'Must be a two-character region code.',
            'documentation_url' => 'https://developers.google.com/maps/documentation/places/web-service/place-details',
            'notes' => 'Optional.',
        ],
    ],
    'capabilities' => [
        'autocomplete',
        'place_details',
        'text_search',
        'nearby_search',
        'place_photo_uri',
        'session_token_generation',
        'configuration_validation',
        'health_check',
    ],
    'dependencies' => [
        'php' => '>=8.1',
        'extensions' => ['curl', 'json'],
    ],
    'health_check_available' => true,
    'configuration_screen_available' => true,
    'owns_sql' => false,
];
