<?php

declare(strict_types=1);

return [
    'name' => 'int_anthropic_agent_sdk',
    'display_name' => 'Anthropic Claude Agent SDK',
    'version' => '1.0.0',
    'type' => 'integration',
    'provider' => 'Anthropic',
    'tool' => 'Claude Agent SDK',
    'description' => 'Controlled PHP-to-Node bridge for Anthropic official Claude Agent SDK.',
    'purpose' => 'Provide Venny I/O with controlled access to Anthropic official Claude Agent SDK while retaining a PHP-facing cartridge boundary, explicit tool grants, bounded turns, isolated settings defaults, configurable working directories, and Business Manager visibility into the privileged agent runtime.',
    'tool_url' => 'https://platform.claude.com/docs/en/agent-sdk/overview',
    'documentation' => [
        'https://platform.claude.com/docs/en/agent-sdk/overview',
        'https://github.com/anthropics/claude-agent-sdk-typescript',
        'https://www.npmjs.com/package/@anthropic-ai/claude-agent-sdk',
    ],
    'configuration' => [
        [
            'key' => 'v_ANTHROPIC_API_KEY',
            'label' => 'Anthropic API Key',
            'required' => true,
            'secret' => true,
            'purpose' => 'Authenticates Claude Agent SDK model requests when using Anthropic API credentials.',
            'where_to_obtain' => 'Anthropic Console API keys.',
            'setup_instructions' => [
                'Create/select the Anthropic project/workspace for Venny agent execution.',
                'Create an API key appropriate to the agent workload.',
                'Store it as v_ANTHROPIC_API_KEY.',
                'Never expose it to client-side code or source control.',
            ],
            'expected_format' => 'Anthropic-generated secret key; commonly sk-ant-...',
            'validation_guidance' => 'Must be non-empty and valid for the intended account.',
            'documentation_url' => 'https://platform.claude.com/docs/en/api/getting-started',
            'notes' => 'Secret.',
        ],
        [
            'key' => 'v_CLAUDE_AGENT_NODE_BINARY',
            'label' => 'Node.js Binary',
            'required' => false,
            'secret' => false,
            'purpose' => 'Selects the Node.js executable used to run the official TypeScript Agent SDK bridge.',
            'where_to_obtain' => 'Installed Node.js 20+ runtime on the Venny worker/dyno/container.',
            'setup_instructions' => [
                'Install a supported Node.js runtime in the execution environment.',
                'Verify it with node --version.',
                'Leave unset when node is resolvable through PATH.',
                'Otherwise store the absolute executable path as v_CLAUDE_AGENT_NODE_BINARY.',
            ],
            'expected_format' => 'node or /usr/local/bin/node',
            'validation_guidance' => 'Executable should report a supported Node.js version.',
            'documentation_url' => 'https://www.npmjs.com/package/@anthropic-ai/claude-agent-sdk',
            'notes' => 'The Agent SDK runtime is not native PHP.',
        ],
        [
            'key' => 'v_CLAUDE_AGENT_WORKING_DIRECTORY',
            'label' => 'Default Agent Working Directory',
            'required' => false,
            'secret' => false,
            'purpose' => 'Bounds the default filesystem location used by tool-enabled agent workflows.',
            'where_to_obtain' => 'Choose a dedicated readable directory in the Venny runtime.',
            'setup_instructions' => [
                'Create/select the narrowest directory the agent needs.',
                'Ensure the Venny worker user has only the required filesystem permissions.',
                'Avoid using filesystem root, the user home directory, or broad secret-containing paths.',
                'Store the absolute path as v_CLAUDE_AGENT_WORKING_DIRECTORY.',
            ],
            'expected_format' => '/app/workspaces/agent-task',
            'validation_guidance' => 'Must exist and be readable. Apply least privilege at the OS/container layer.',
            'documentation_url' => 'https://platform.claude.com/docs/en/agent-sdk/overview',
            'notes' => 'Strongly recommended before enabling filesystem or shell tools.',
        ],
        [
            'key' => 'v_CLAUDE_AGENT_DEFAULT_MODEL',
            'label' => 'Default Agent Model',
            'required' => false,
            'secret' => false,
            'purpose' => 'Provides a default Claude model for agent queries.',
            'where_to_obtain' => 'Anthropic current model documentation.',
            'setup_instructions' => [
                'Choose a model suitable for the intended agent workload.',
                'Store the exact model identifier as v_CLAUDE_AGENT_DEFAULT_MODEL.',
                'Leave unset if callers explicitly select models.',
            ],
            'expected_format' => 'Example: claude-sonnet-5',
            'validation_guidance' => 'Must be available to the configured account.',
            'documentation_url' => 'https://platform.claude.com/docs/en/about-claude/models/overview',
            'notes' => 'Model availability changes over time.',
        ],
        [
            'key' => 'v_CLAUDE_AGENT_PERMISSION_MODE',
            'label' => 'Default Agent Permission Mode',
            'required' => false,
            'secret' => false,
            'purpose' => 'Controls the default Agent SDK permission behavior.',
            'where_to_obtain' => 'Choose from permission modes supported by the installed Agent SDK.',
            'setup_instructions' => [
                'Keep default unless a workflow requires a different documented permission mode.',
                'Store the exact documented mode as v_CLAUDE_AGENT_PERMISSION_MODE.',
                'Do not use bypassPermissions; this cartridge rejects it in v1.',
            ],
            'expected_format' => 'default',
            'validation_guidance' => 'bypassPermissions is explicitly rejected by cartridge policy.',
            'documentation_url' => 'https://platform.claude.com/docs/en/agent-sdk/overview',
            'notes' => 'Permission bypass requires a future explicit Venny privileged-execution design.',
        ],
        [
            'key' => 'v_CLAUDE_AGENT_MAX_TURNS',
            'label' => 'Default Maximum Agent Turns',
            'required' => false,
            'secret' => false,
            'purpose' => 'Bounds default autonomous execution length.',
            'where_to_obtain' => 'Set based on the workflow complexity and cost/risk envelope.',
            'setup_instructions' => [
                'Choose a conservative maximum number of turns.',
                'Store a positive integer as v_CLAUDE_AGENT_MAX_TURNS.',
                'Leave unset to use 8.',
            ],
            'expected_format' => '8',
            'validation_guidance' => 'Must be a positive integer.',
            'documentation_url' => 'https://platform.claude.com/docs/en/agent-sdk/overview',
            'notes' => 'Per-query callers may request a different bounded value.',
        ],
    ],
    'capabilities' => [
        'agent_query',
        'agent_event_stream',
        'working_directory',
        'built_in_tool_allowlist',
        'tool_permission_mode',
        'session_isolation_defaults',
        'configuration_validation',
        'health_check',
    ],
    'dependencies' => [
        'php' => '>=8.1',
        'node' => '>=20',
        'npm' => [
            '@anthropic-ai/claude-agent-sdk' => '^0.3.250',
        ],
    ],
    'health_check_available' => true,
    'configuration_screen_available' => true,
    'owns_sql' => false,
    'security_defaults' => [
        'tools' => [],
        'setting_sources' => [],
        'persist_session' => false,
        'permission_bypass_allowed' => false,
    ],
];
