<?php

declare(strict_types=1);

return [
    'name' => 'int_anthropic_claude',
    'display_name' => 'Anthropic Claude API',
    'version' => '1.0.0',
    'type' => 'integration',
    'provider' => 'Anthropic',
    'tool' => 'Claude API',
    'description' => 'Native PHP Claude API provider for Venny I/O.',
    'purpose' => 'Provide Venny I/O with an official-SDK-backed Claude model adapter for messages, streaming, token counting, tool definitions, structured output configuration, prompt caching controls, files, and normalized provider diagnostics without moving application prompts, memory, business workflow, or tool execution into the provider cartridge.',
    'tool_url' => 'https://platform.claude.com/docs/en/api/overview',
    'documentation' => [
        'https://platform.claude.com/docs/en/api/overview',
        'https://platform.claude.com/docs/en/api/php',
        'https://github.com/anthropics/anthropic-sdk-php',
    ],
    'configuration' => [
        [
            'key' => 'v_ANTHROPIC_API_KEY',
            'label' => 'Anthropic API Key',
            'required' => true,
            'secret' => true,
            'purpose' => 'Authenticates server-side Venny I/O requests to the Claude API.',
            'where_to_obtain' => 'Anthropic Console API keys area.',
            'setup_instructions' => [
                'Sign in to the Anthropic Console.',
                'Select the Anthropic workspace/project Venny I/O should use.',
                'Create an API key with the access appropriate to this integration.',
                'Copy the key once and store it as v_ANTHROPIC_API_KEY.',
                'Do not place the key in source control or browser/mobile code.',
            ],
            'expected_format' => 'Anthropic-generated secret key; commonly sk-ant-...',
            'validation_guidance' => 'Must be non-empty and valid for the intended Anthropic workspace.',
            'documentation_url' => 'https://platform.claude.com/docs/en/api/getting-started',
            'notes' => 'Secret.',
        ],
        [
            'key' => 'v_ANTHROPIC_DEFAULT_MODEL',
            'label' => 'Default Claude Model',
            'required' => false,
            'secret' => false,
            'purpose' => 'Provides a default Claude model when a Venny request does not specify one.',
            'where_to_obtain' => 'Choose a currently supported model from Anthropic model documentation for the application workload.',
            'setup_instructions' => [
                'Review Anthropic current model documentation.',
                'Choose the default model appropriate to the Venny workload.',
                'Store the exact model identifier as v_ANTHROPIC_DEFAULT_MODEL.',
                'Leave unset if every caller must explicitly choose a model.',
            ],
            'expected_format' => 'Example: claude-sonnet-5',
            'validation_guidance' => 'Must be a model available to the configured Anthropic account.',
            'documentation_url' => 'https://platform.claude.com/docs/en/about-claude/models/overview',
            'notes' => 'Model catalogs evolve; do not treat the example as permanently current.',
        ],
        [
            'key' => 'v_ANTHROPIC_MAX_TOKENS',
            'label' => 'Default Maximum Output Tokens',
            'required' => false,
            'secret' => false,
            'purpose' => 'Sets the default maximum output-token budget for requests that omit max_tokens.',
            'where_to_obtain' => 'Choose based on application response requirements and model limits.',
            'setup_instructions' => [
                'Determine the normal maximum output size for the application.',
                'Store a positive integer as v_ANTHROPIC_MAX_TOKENS.',
                'Leave unset to use the cartridge default of 4096.',
            ],
            'expected_format' => '4096',
            'validation_guidance' => 'Positive integer and within applicable model limits.',
            'documentation_url' => 'https://platform.claude.com/docs/en/api/messages/create',
            'notes' => 'This is a Venny default, not an Anthropic account limit.',
        ],
    ],
    'capabilities' => [
        'messages',
        'stream_messages',
        'count_tokens',
        'tool_use',
        'structured_outputs',
        'prompt_caching',
        'files',
        'provider_diagnostics',
        'health_check',
    ],
    'dependencies' => [
        'php' => '>=8.1',
        'composer' => [
            'anthropic-ai/sdk' => '^0.44.0',
            'guzzlehttp/guzzle' => '^7.0',
        ],
    ],
    'health_check_available' => true,
    'configuration_screen_available' => true,
    'owns_sql' => false,
];
