-- app_venny_storefront schema

CREATE TABLE IF NOT EXISTS catalogs (
id UUID DEFAULT gen_random_uuid(),
catalog_id VARCHAR(64) NOT NULL UNIQUE PRIMARY KEY,
catalog_attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
catalog_online BOOLEAN NOT NULL,
catalog_public BOOLEAN NOT NULL,
catalog_name VARCHAR(100) NOT NULL,
catalog_description VARCHAR(280) NOT NULL,
catalog_slug VARCHAR(100) NOT NULL,
catalog_images JSONB NULL,
created_by_user_id VARCHAR(64) NOT NULL DEFAULT 'user_8301',
created_for_app_id VARCHAR(64) NOT NULL DEFAULT 'app_8301',
event_id VARCHAR(64) NOT NULL DEFAULT 'event_8301',
process_id VARCHAR(64) NOT NULL DEFAULT 'process_8301',
access VARCHAR(30) NOT NULL DEFAULT 'private',
status VARCHAR(30) NOT NULL DEFAULT 'active',
active INT NOT NULL DEFAULT 1,
time_started TIMESTAMPTZ NOT NULL DEFAULT NOW(),
time_updated TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS categories (
id UUID DEFAULT gen_random_uuid(),
category_id VARCHAR(64) NOT NULL UNIQUE PRIMARY KEY,
category_attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
category_catalog_id VARCHAR(64) NOT NULL,
category_online BOOLEAN NOT NULL,
category_public BOOLEAN NOT NULL,
category_name VARCHAR(100) NOT NULL,
category_description VARCHAR(280) NOT NULL,
category_slug VARCHAR(100) NOT NULL,
category_images JSONB NULL,
created_by_user_id VARCHAR(64) NOT NULL DEFAULT 'user_8301',
created_for_app_id VARCHAR(64) NOT NULL DEFAULT 'app_8301',
event_id VARCHAR(64) NOT NULL DEFAULT 'event_8301',
process_id VARCHAR(64) NOT NULL DEFAULT 'process_8301',
access VARCHAR(30) NOT NULL DEFAULT 'private',
status VARCHAR(30) NOT NULL DEFAULT 'active',
active INT NOT NULL DEFAULT 1,
time_started TIMESTAMPTZ NOT NULL DEFAULT NOW(),
time_updated TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS products (
id UUID DEFAULT gen_random_uuid(),
product_id VARCHAR(64) NOT NULL UNIQUE PRIMARY KEY,
product_attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
product_catalog_id VARCHAR(64) NOT NULL,
product_category_id VARCHAR(64) NOT NULL,
product_online BOOLEAN NOT NULL,
product_public BOOLEAN NOT NULL,
product_name VARCHAR(100) NOT NULL,
product_description VARCHAR(280) NOT NULL,
product_slug VARCHAR(100) NOT NULL,
product_images JSONB NULL,
product_sku VARCHAR(100) NOT NULL,
product_base_price NUMERIC(12,2) NOT NULL,
product_inventory INT NOT NULL,
product_manufacturer VARCHAR(280) NULL,
product_weight INT NULL,
created_by_user_id VARCHAR(64) NOT NULL DEFAULT 'user_8301',
created_for_app_id VARCHAR(64) NOT NULL DEFAULT 'app_8301',
event_id VARCHAR(64) NOT NULL DEFAULT 'event_8301',
process_id VARCHAR(64) NOT NULL DEFAULT 'process_8301',
access VARCHAR(30) NOT NULL DEFAULT 'private',
status VARCHAR(30) NOT NULL DEFAULT 'active',
active INT NOT NULL DEFAULT 1,
time_started TIMESTAMPTZ NOT NULL DEFAULT NOW(),
time_updated TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS items (
id UUID DEFAULT gen_random_uuid(),
item_id VARCHAR(64) NOT NULL UNIQUE PRIMARY KEY,
item_attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
item_catalog_id VARCHAR(64) NOT NULL,
item_category_id VARCHAR(64) NOT NULL,
item_product_id VARCHAR(64) NOT NULL,
item_serial_number VARCHAR(64) NULL,
item_quantity INT NULL,
item_sale_price NUMERIC(12,2) NULL,
item_size INT NULL,
item_color VARCHAR(30) NULL,
created_by_user_id VARCHAR(64) NOT NULL DEFAULT 'user_8301',
created_for_app_id VARCHAR(64) NOT NULL DEFAULT 'app_8301',
event_id VARCHAR(64) NOT NULL DEFAULT 'event_8301',
process_id VARCHAR(64) NOT NULL DEFAULT 'process_8301',
access VARCHAR(30) NOT NULL DEFAULT 'private',
status VARCHAR(30) NOT NULL DEFAULT 'active',
active INT NOT NULL DEFAULT 1,
time_started TIMESTAMPTZ NOT NULL DEFAULT NOW(),
time_updated TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
